core:
    namespace: "testing"
    serviceName: "db"
    statefulset:
      restartPolicy: "Always"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - image: "postgres"
          tag: "latest"
          containerPort: "3000"
          resources:
            requests:
              cpu: 400m
              memory: 128Mi
            limits:
              cpu: 800m
              memory: 1200Mi
          envFrom:
            - secretRef:
                name: db-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data 


    service:
      - name: db-svc
        selector: db
        type: ClusterIP
        ports:
          - port: 3000
            targetPort: 3000
            protocol: TCP

    secret:
      name: db-secret
      type: Opaque
      data:
        POSTGRES_USER: YWRtaW4=
        POSTGRES_PASSWORD: YWRtaW4=
        POSTGRES_DB: YXBwZGI=


    pv:
      enabled: true
      name: local-pv
      storage: 1Gi
      accessMode: ReadWriteOnce
      reclaimPolicy: Retain
      hostPath: /mnt/disks/postgres-0

    pvc:
      enabled: true
      name: postgres-pvc
      storage: 1Gi
      accessMode: ReadWriteOnce

