name: CI

on:
  push:
    branches: [master]

env:
  REGISTRY: docker.io
  IMAGE_NAME: mohamedalaaelsafy/devops-task-app

jobs:
  lint-and-build:
    name: Lint and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js (for JS linting)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install YAML and JS linters
        run: |
          npm install -g eslint

      - name: Lint 
        run: |
          eslint "**/*.js" || true  

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get short commit SHA
        id: vars
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}

  helm-lint:
    name: Helm Lint
    runs-on: ubuntu-latest
    needs: lint-and-build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Lint Helm charts
        run: |
          helm lint DevOps/k8s/charts/app
          helm lint DevOps/k8s/charts/db