{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    app: {{ .Values.appName | default "my-app" }}
type: {{ .Values.secret.type | default "Opaque" }}
data:
  {{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}